# Generated by Django 5.1.4 on 2026-05-12 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('deck', models.TextField(blank=True, null=True, verbose_name='부제목')),
                ('slug', models.TextField(blank=True, null=True, verbose_name='URL 슬러그')),
                ('body', models.TextField(verbose_name='본문 (레거시)')),
                ('body_markdown', models.TextField(verbose_name='마크다운 본문')),
                ('body_html', models.TextField(blank=True, null=True, verbose_name='HTML 본문')),
                ('category', models.TextField(choices=[('국내', '국내'), ('글로벌', '글로벌')], verbose_name='카테고리')),
                ('tags', models.JSONField(default=list, verbose_name='태그')),
                ('match_reason', models.TextField(blank=True, null=True, verbose_name='짝짓기 사유')),
                ('source_titles', models.JSONField(default=list, verbose_name='원본 제목들')),
                ('source_urls', models.JSONField(default=list, verbose_name='원본 URL들')),
                ('validation_passed', models.BooleanField(default=False, verbose_name='검수 통과')),
                ('validation_issues', models.JSONField(blank=True, null=True, verbose_name='검수 이슈')),
                ('input_tokens', models.IntegerField(blank=True, null=True, verbose_name='입력 토큰')),
                ('output_tokens', models.IntegerField(blank=True, null=True, verbose_name='출력 토큰')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='비용(USD)')),
                ('publish_status', models.TextField(choices=[('draft', '초안'), ('published', '발행됨'), ('archived', '보관됨')], default='draft', verbose_name='발행 상태')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='발행 시각')),
                ('is_featured', models.BooleanField(default=False, verbose_name='추천 기사')),
                ('is_hot', models.BooleanField(default=False, verbose_name='인기 기사')),
                ('read_minutes', models.IntegerField(default=0, verbose_name='읽는 시간(분)')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 시각')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='수정 시각')),
                ('pipeline_run_id', models.BigIntegerField(blank=True, null=True, verbose_name='파이프라인 실행 ID')),
            ],
            options={
                'verbose_name': '기사',
                'verbose_name_plural': '기사들',
                'db_table': 'generated_articles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_article_created'), models.Index(fields=['slug'], name='idx_article_slug'), models.Index(fields=['category'], name='idx_article_category'), models.Index(fields=['publish_status'], name='idx_article_status')],
            },
        ),
    ]
