# Generated by Django 5.1.4 on 2026-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='이미지 URL'),
        ),
    ]
